system:
  ip: 0.0.0.0
  port: 8080
  env: dev
  gin_mode: release

log:
  app: blog_server
  dir: logs

jwt:
  expire: 3       #单位小时
  secret: skw
  issuer: xiaosong
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0

db:  #读库
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blog
  debug: false
  source: mysql

db1:  #写库
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blog
  debug: false
  source: mysql

site_info:
  created_at: "2025-7-25"
  bei_an:
  title: 下次一定的个人博客
  qq_image:
  version: 1.0.0
  email: 2083933996@qq.com
  wechat_image:
  name: 下次一定
  job: 后端开发
  addr: 山东青岛
  slogan: golang
  slogan_en: GOLANG
  web:
  bilibili_url:
  gitee_url:
  github_url:

qq:
  app_id: "1112383751"
  key: VURxpNMnpwPKsJPo
  redirect:

email:
  host: smtp.qq.com
  port: 465
  user: 2083933996@qq.com
  password: ebwamormxkmqccje
  default_from_email: "下次一定"
  use_ssl: true
  user_tls: true

qiniu:
  enable: true
  access_key: D3bqvd7CrziBb7S70D-0dQHReO-h0xwperqoVUbg
  secret_key: sv2jm0MGuHM4bn8ca_6qjBTItOlxxjDm4bKq1fY8
  bucket: xiaciyiding
  cdn: http://t01tk5089.hn-bkt.clouddn.com/
  zone: z2
  prefix: "gvb"
  size: 5

upload:
  size: 2
  path: uploads/file

es:
  username: elastic
  password: 123456

